// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/admin/v1alpha/resources.proto

package com.google.analytics.admin.v1alpha;

public interface ConversionEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.admin.v1alpha.ConversionEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Output only. Resource name of this conversion event.
   * Format: properties/{property}/conversionEvents/{conversion_event}
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Output only. Resource name of this conversion event.
   * Format: properties/{property}/conversionEvents/{conversion_event}
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Immutable. The event name for this conversion event.
   * Examples: 'click', 'purchase'
   * </pre>
   *
   * <code>string event_name = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The eventName.
   */
  java.lang.String getEventName();
  /**
   * <pre>
   * Immutable. The event name for this conversion event.
   * Examples: 'click', 'purchase'
   * </pre>
   *
   * <code>string event_name = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <pre>
   * Output only. Time when this conversion event was created in the property.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   * Output only. Time when this conversion event was created in the property.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   * Output only. Time when this conversion event was created in the property.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   * Output only. If set, this event can currently be deleted via DeleteConversionEvent.
   * </pre>
   *
   * <code>bool is_deletable = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The isDeletable.
   */
  boolean getIsDeletable();
}
