// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/admin/v1alpha/analytics_admin.proto

package com.google.analytics.admin.v1alpha;

public interface CreateWebDataStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.admin.v1alpha.CreateWebDataStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The web stream to create.
   * </pre>
   *
   * <code>.google.analytics.admin.v1alpha.WebDataStream web_data_stream = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the webDataStream field is set.
   */
  boolean hasWebDataStream();
  /**
   * <pre>
   * Required. The web stream to create.
   * </pre>
   *
   * <code>.google.analytics.admin.v1alpha.WebDataStream web_data_stream = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The webDataStream.
   */
  com.google.analytics.admin.v1alpha.WebDataStream getWebDataStream();
  /**
   * <pre>
   * Required. The web stream to create.
   * </pre>
   *
   * <code>.google.analytics.admin.v1alpha.WebDataStream web_data_stream = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.analytics.admin.v1alpha.WebDataStreamOrBuilder getWebDataStreamOrBuilder();

  /**
   * <pre>
   * Required. The parent resource where this web data stream will be created.
   * Format: properties/123
   * </pre>
   *
   * <code>string parent = 2 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Required. The parent resource where this web data stream will be created.
   * Format: properties/123
   * </pre>
   *
   * <code>string parent = 2 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();
}
