// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/admin/v1alpha/analytics_admin.proto

package com.google.analytics.admin.v1alpha;

public interface ListWebDataStreamsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.admin.v1alpha.ListWebDataStreamsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.WebDataStream web_data_streams = 1;</code>
   */
  java.util.List<com.google.analytics.admin.v1alpha.WebDataStream> 
      getWebDataStreamsList();
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.WebDataStream web_data_streams = 1;</code>
   */
  com.google.analytics.admin.v1alpha.WebDataStream getWebDataStreams(int index);
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.WebDataStream web_data_streams = 1;</code>
   */
  int getWebDataStreamsCount();
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.WebDataStream web_data_streams = 1;</code>
   */
  java.util.List<? extends com.google.analytics.admin.v1alpha.WebDataStreamOrBuilder> 
      getWebDataStreamsOrBuilderList();
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.WebDataStream web_data_streams = 1;</code>
   */
  com.google.analytics.admin.v1alpha.WebDataStreamOrBuilder getWebDataStreamsOrBuilder(
      int index);

  /**
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
