// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/analytics/admin/v1alpha/analytics_admin.proto

package com.google.analytics.admin.v1alpha;

public interface ListIosAppDataStreamsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.analytics.admin.v1alpha.ListIosAppDataStreamsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.IosAppDataStream ios_app_data_streams = 1;</code>
   */
  java.util.List<com.google.analytics.admin.v1alpha.IosAppDataStream> 
      getIosAppDataStreamsList();
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.IosAppDataStream ios_app_data_streams = 1;</code>
   */
  com.google.analytics.admin.v1alpha.IosAppDataStream getIosAppDataStreams(int index);
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.IosAppDataStream ios_app_data_streams = 1;</code>
   */
  int getIosAppDataStreamsCount();
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.IosAppDataStream ios_app_data_streams = 1;</code>
   */
  java.util.List<? extends com.google.analytics.admin.v1alpha.IosAppDataStreamOrBuilder> 
      getIosAppDataStreamsOrBuilderList();
  /**
   * <pre>
   * Results that matched the filter criteria and were accessible to the caller.
   * </pre>
   *
   * <code>repeated .google.analytics.admin.v1alpha.IosAppDataStream ios_app_data_streams = 1;</code>
   */
  com.google.analytics.admin.v1alpha.IosAppDataStreamOrBuilder getIosAppDataStreamsOrBuilder(
      int index);

  /**
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
